### ISSUE TITLE
M600: Wait after extrusion before resuming the print

### ISSUE THREAD

**Issue by andrivet** [andrivet/ADVi3pp#112]
Alexander Westphal (on Patreon):

Tested M600 today, something i noticed is that after the extrusion is finished it moves directly to the print again and drags the extrusion with it. Is it possible to add a button to the lcd "extrusion removed" and let the extruder wait on the position till the button is pressed?

**Comment by noel2763** [comment]
Hi Andrivet, first of all I want to thank you for the firmware. Loving my Maker Select Plus more now. I'm having the same issue as Alexander. I just installed ADVi3++ a month ago. Where can I find the solution to his question?

**Comment by andrivet** [comment]
@noel2763 Thanks. But please do not abuse the issues to ask for support. I am doing support only on Patreon. I delete this comment and yours since they do not follow the code of conduct.

**Comment by noel2763** [comment]
Sorry Andivet I am new and didn't know about the code of conduct. Anyway, the lcd screen says insert filament and press resume. It won't extrude filament unless I press resume arrow, then it goes straight to print. No option on the lcd to resume or extrude more filament. Thanks a lot for the reply. 


Sent from my T-Mobile 4G LTE Device
-------- Original message --------From: Sebastien Andrivet <notifications@github.com> Date: 8/23/18  7:10 AM  (GMT-08:00) To: andrivet/ADVi3pp-Marlin <ADVi3pp-Marlin@noreply.github.com> Cc: noel2763 <ronn2763@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [andrivet/ADVi3pp-Marlin] M600: Wait after extrusion before
  resuming the print (#112) 
@noel2763 Thanks. But please do not abuse the issues to ask for support. I am doing support only on Patreon. I delete this comment and yours since they do not follow the code of conduct.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/andrivet/ADVi3pp-Marlin","title":"andrivet/ADVi3pp-Marlin","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/andrivet/ADVi3pp-Marlin"}},"updates":{"snippets":[{"icon":"PERSON","message":"@andrivet in #112: @noel2763 Thanks. But please do not abuse the issues to ask for support. I am doing support only on Patreon. I delete this comment and yours since they do not follow the code of conduct."}],"action":{"name":"View Issue","url":"https://github.com/andrivet/ADVi3pp-Marlin/issues/112#issuecomment-415427587"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/andrivet/ADVi3pp-Marlin/issues/112#issuecomment-415427587",
"url": "https://github.com/andrivet/ADVi3pp-Marlin/issues/112#issuecomment-415427587",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [andrivet/ADVi3pp-Marlin] M600: Wait after extrusion before resuming the print (#112)",
"sections": [
{
"text": "",
"activityTitle": "**Sebastien Andrivet**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@andrivet",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"andrivet/ADVi3pp-Marlin\",\n\"issueId\": 112,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"andrivet/ADVi3pp-Marlin\",\n\"issueId\": 112\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/andrivet/ADVi3pp-Marlin/issues/112#issuecomment-415427587"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 330475041\n}"
}
],
"themeColor": "26292E"
}
]
