### ISSUE TITLE
Thank you for your efforts here... the software is looking great!  I did notice a problem with my extruder temperatures being erratic. So much to the point I regretted installing it... (I know, it is a beta). I tried to reload and I made things worse... I now have a blinking (twice every 4-5 seconds) red led near the ribbon cable socket. Any idea what that might be (BIOS error?). Any ideas welcome (I am a supporter).

### ISSUE THREAD

**Issue by Prexsys-Beach** [andrivet/ADVi3pp#124]
Thank you for submitting your feedback to the ADVi3++ project.
Please use one of the templates below to fill out this box.

------------------------------------------------------------
### Feature Request
Please put [FR] in the issue title: `[FR] Add-on that goes 'ping'`

------------------------------------------------------------
### Bug Repo
- Description: ---
- Expected behaviour: ---
- Actual behaviour: ---
- Steps to reproduce:
  - Do this
  - Do that

------------------------------------------------------------
### Bug Report Tips
- Format text with: **bold**, _italic_, `code`.
- Format C++ with three backticks, plus "cpp":
```cpp
void my_function(bool do_it) {
  // Hold this spot
}
```

**Comment by andrivet** [comment]
So again and again: This is not the right place to ask for support. For that, ask your question on the ADVi3++ Facebook page or on Patreon (since your are a supporter). Issues here are only for bug report and new feature request. In all cases, you have to fill the template. It is a very bad idea to put tones of text in the title. It makes me upset. For these reasons, I am closing this issue.
