### ISSUE TITLE
Feature idea: configure distance between sensor and nozzle on display

### ISSUE THREAD

**Issue by ghost** [andrivet/ADVi3pp#131]
As people have different setups regarding extruder hardware, they need to configure the distance between the sensor and the nozzle. It would be a great feature if this could be done in the gui.

**Comment by andrivet** [comment]
Please fill the template, it is now mandatory. Otherwise, I will close this issue. I also think it is a duplicate of #125

**Comment by ghost** [comment]
You are quite right. Issue #125  is the same.

**Comment by andrivet** [comment]
Language please. I am deleting your comment because of that. And if your are not able to fill properly an issue, do not create an issue.

**Comment by Bosbessenbasje** [comment]
Apologies for mixing up English slang. I looked it up, it is only mildly considered bad language. Nevertheless, you are right. I will use 'neck' in the future as that is not considered bad language.

Regarding filling in a form properly. I am a profession software engineer, working with issue trackers 40 hours in the week. I do know how to fill in a form. However, doing it on an iPhone was nearly impossible, as you can not see the form in total, nor is it obvious that it is a form in the first place. I do understand the reason for having guidelines, but your remark offended me. I was just trying to help to make you excellent efforts and work even better. For that same reason I have sent you money. I do not wish for special treatment in return, but a normal communication methods I do prefer. I have been promoting your work on the internet on several sites, but if you don't like that, I can easily quit with that.

Just my thoughts on the matter and therefore offline.

Marcel/bosbessenbasje

Verstuurd vanaf mijn iPad

Op 3 jun. 2018 om 20:42 heeft Sebastien Andrivet <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Language please. I am deleting your comment because of that. And if your are not able to fill properly an issue, do not create an issue.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fandrivet%2FADVi3pp-Marlin%2Fissues%2F131%23issuecomment-394182352&data=01%7C01%7Cmarcel.boom%40newayselectronics.com%7Cb0c710218f0e4df5a6ff08d5c981c215%7Cec7e8b70c75743cc90e8805ad967f616%7C1&sdata=vlxO1WPO5ZsN503gJzcyephpHuJV33Ao%2FHjm33Nw8kU%3D&reserved=0>, or mute the thread<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FASwYsOUMBJSzNBnEpzNJ7aUA8KL-Uo6Pks5t5C4TgaJpZM4UX1Cp&data=01%7C01%7Cmarcel.boom%40newayselectronics.com%7Cb0c710218f0e4df5a6ff08d5c981c215%7Cec7e8b70c75743cc90e8805ad967f616%7C1&sdata=miqiDzwD1XpRP%2FZB%2Fnr44U%2F7GRIq9vaWUzRjGkZUUCQ%3D&reserved=0>.


________________________________
This e-mail and any attachment is confidential and may be legally privileged or otherwise protected from disclosure. If you are not the intended recipient, please notify the sender immediately by returning this e-mail.
Neways Electronics NV is not responsible for the improper or incomplete transmission of any e-mail, or for any delay in its receipt.
________________________________
