### ISSUE TITLE
IPv4 displayed vs. IPv6

### ISSUE THREAD

**Issue by TTVert** [andrivet/ADVi3pp#164]
I saw no option to configure this . The IPv6 is displayed but can IPv4 be displayed instead somehow?

Thanks
Dave

**Comment by andrivet** [comment]
@TTVert I have no idea of what you are talking about. This printer has no network. And please, use the template when submitting issues

**Comment by TTVert** [comment]
You seriously don't know that at the bottom of the display on your firmware there is an IP v6 address displayed?

**Comment by andrivet** [comment]
I assume that you are using OctoPrint, isn't it? This IP is displayed by OctoPrint. Nothing to do with the firmware.

**Comment by TTVert** [comment]
I use repetier.  I never saw any IP info until after the latest firmware of yours.  I will go through all the repetier docs and settings and see where that may be coming from then.   It is displaying the ip v6 at the bottom of the screen while idle w/ no print running.  Unsure how repetier would be doing that but I'll look.

Dave

**Comment by andrivet** [comment]
This is sent by Repetier. Again, the printer has no ethernet connector so it has no notion of IP address. What you see is a message sent by Repetier with the G-Code M117. The IP is the IP of your computer or whatever device you are using with an Ethernet connector.

I stop the conversation here since it is not about an issue but about support.

**Comment by TTVert** [comment]
Fair enough, where is the best place to obtain feature info/support when needed?  i think I saw a paid facebook group?

**Comment by andrivet** [comment]
Patreon. https://www.patreon.com/andrivet
