### ISSUE TITLE
Add a progress bar during printing

### ISSUE THREAD

**Issue by chschmit** [andrivet/ADVi3pp#27]
A progress bar would be great that could be viewed across a room. I use multiple printers and the progress bar on the Wanhao latest firmware worked very well from a visibility standpoint.

**Comment by TTVert** [comment]
I would also like this.  Perhaps put the bar graph where the pause/play/stop icons were before in graph?

**Comment by mpfl** [comment]
This would work very well with the M73 Progress plugin for OctoPrint.

**Comment by andrivet** [comment]
It may look like this:

![main](https://user-images.githubusercontent.com/981049/42286958-e124cade-7fb4-11e8-94cd-841ea36fa885.png)

![print](https://user-images.githubusercontent.com/981049/42286985-f0215d7c-7fb4-11e8-8b6c-d0b5956c8986.png)

**Comment by TTVert** [comment]
Is the green the portion still to be completed?  If so would it be better to have a white or red box w/ teh green showing what is completed? 

UPDATE: Remove image with a wrong size

**Comment by chschmit** [comment]
I agree with this revised approach. Conventional progress bars show completeness from left to right generally with a bolder color signifying the amount complete. White, gray or transparent are usually the portion of the bar that isn't completed yet. 

On July 4, 2018 9:17:27 AM PDT, TTVert <notifications@github.com> wrote:
>Is the green the portion still to be completed?  If so would it be
>better to have a white or red box w/ teh green showing what is
>completed?  
>![image](https://user-images.githubusercontent.com/24374538/42287399-d1bbcc3e-7f7b-11e8-962e-65178b45e8bb.png)
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/andrivet/ADVi3pp-Marlin/issues/27#issuecomment-402520066

-- 
Sent from my Android Google Pixel.

**Comment by andrivet** [comment]
OK, so it may looks like this:

![main](https://user-images.githubusercontent.com/981049/42334441-89f8d696-807d-11e8-8510-1e1b4c8df16a.png)

![print](https://user-images.githubusercontent.com/981049/42334488-a220e268-807d-11e8-87ea-99f294186bcd.png)

**Comment by TTVert** [comment]
Much better!  Any way to incorporate % done like my image showed?

**Comment by chschmit** [comment]
Agreed. Simple, yet very usable. 

On July 5, 2018 10:22:38 AM PDT, TTVert <notifications@github.com> wrote:
>Much better!
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/andrivet/ADVi3pp-Marlin/issues/27#issuecomment-402794554

-- 
Sent from my Android Google Pixel.

**Comment by Deose** [comment]
I think a ETA would be more important than a %, or a time elapsed + a % completed.

**Comment by andrivet** [comment]
@Deose "I think..." Why do you think it is better? And computing ETA is a very complex problem. How do you see that?

**Comment by TTVert** [comment]
Could you not use the ETE/ETA reported from the slicer?   Maybe not all slicers do this but repetier adds Gcode for this in the job.

**Comment by andrivet** [comment]
@TTVert Outputting ETA/ETE on the LCD is already possible with the M117 support (there are already OctoPrint's plugins for that). Regarding G-Codes, there is [M73](https://reprap.org/wiki/G-code#M73:_Set_build_percentage), supported by Marlin. I am not aware of any G-Code with ETA. And even if the slicer gives ETA information, it will not be accurate and I will then get many bug reports saying the ETA is wrong (this is what happened with OctoPrint). And I want to avoid such situation. 

So if someone has a reliable (and documented) way of giving a reliable ETA, I may implement this. For the moment, it is no.

UPDATE: Marlin does support M73

**Comment by TTVert** [comment]
Personally I'm fine w/ percentage and using repetier I know first hand how inaccurate ETA/ETE can be.

**Comment by churd83** [comment]
Personally as long as it completes I'm good

**Comment by Deose** [comment]
@andrivet I think an ETA is better than a progress bar or a % because isn't the whole purpose of showing the % completed or a progress bar to show "How close it is to being completed"? If the purpose of said things are to see how far along it is, a straight ETA not old tells that as well, but gives extra information as well.

I know absolutely nothing about implementing these things or coding it, I just saw people commenting on the markups and wanted to throw my 2¢ out there.

Like somebody else said, Cura has a "Total time estimated" and "time estimated remaining" when it prints. Even the stock Maker Select plus has a time gauge on it, I believe. I don't fully remember now (as I always used Print from PC via USB), but think it has some sort of count down (or count up) function built it.

Freecoding an ETA function by hand could be difficult, and like you said, might be a lot of work if you don't want to deal with people submitting bugs about it. However, a % of completed (I guess it could divide how many lines it has down, divide it by how many lines there are total, and multiply it by 100) and a running timer from when it starts printing, together would make it so people could estimate how much longer. It would be quite a rough estimate, since different layers are different sizes, but it's at least some way to gauge how long a print has left.

**Comment by chschmit** [comment]
As the originator of this request I also desire an ETA status but due to the inaccuracies of any ETA calculation I've seen so far I was hoping to have a progress bar that can be viewed from across the room similar to the Wanhao original firmware.

Let's start with a progress bar and if there is an ETA implementation that actually works in the future I'd support that as text overlaying a progress bar. 

On August 3, 2018 5:47:08 PM PDT, Deose <notifications@github.com> wrote:
>@andrivet I think an ETA is better than a progress bar or a % because
>isn't the whole purpose of showing the % completed or a progress bar to
>show "How close it is to being completed"? If the purpose of said
>things are to see how far along it is, a straight ETA not old tells
>that as well, but gives extra information as well.
>
>I know absolutely nothing about implementing these things or coding it,
>I just saw people commenting on the markups and wanted to throw my 2¢
>out there.
>
>Like somebody else said, Cura has a "Total time estimated" and "time
>estimated remaining" when it prints. Even the stock Maker Select plus
>has a time gauge on it, I believe. I don't fully remember now (as I
>always used Print from PC via USB), but think it has some sort of count
>down (or count up) function built it.
>
>Freecoding an ETA function by hand could be difficult, and like you
>said, might be a lot of work if you don't want to deal with people
>submitting bugs about it. However, a % of completed (I guess it could
>divide how many lines it has down, divide it by how many lines there
>are total, and multiply it by 100) and a running timer from when it
>starts printing, together would make it so people could estimate how
>much longer. It would be quite a rough estimate, since different layers
>are different sizes, but it's at least some way to gauge how long a
>print has left.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/andrivet/ADVi3pp-Marlin/issues/27#issuecomment-410409259

-- 
Sent from my Android Google Pixel.

**Comment by therevoman** [comment]
I would love to see a semi accurate ETA but understand how difficult that problem is.  Have you ever watched the progress bar of a large file transfer oon your computer? The ETA changes regularly.  That is because they make guesses on transfer speed in the beginning and then use a rolling average transfer rate later. So much math and guessing.

I really like knowing how many layers remain and would appreciate a progress bar based on number of layers.

For the original poster, just think of the different settings your slicer gives you depending on the layer being printed, along with the differences in a defined speeds and actual speeds...  well, it goes way beyond that. 

As much as I'd like to see an ETA progress bar, I'm with the developer on avoiding it's addition.

**Comment by TTVert** [comment]
repetier also shows layers, it cycled through that, eta, etc.

**Comment by andrivet** [comment]
Implement as the same time M73 - LCD_SET_PROGRESS_MANUALLY and LCD_PROGRESS_BAR

**Comment by andrivet** [comment]
Implement also M250 - LCD Contrast
