### ISSUE TITLE
G28 Home

### ISSUE THREAD

**Issue by Titus142** [andrivet/ADVi3pp#77]
### Bug Report
- Description: Z homes on center of build place instead of relative position
- Expected behaviour: When G2 called at start of Gcode I expect to home Z at X and Y home, or if pressed on LCD to home Z in relative XY position
- Actual behaviour: XY moves to center of build plate then homes Z, LCD control for Z home or all home also only homes Z in center of build plate

Start code is as follows:

G21 ;metric values
G90 ;absolute positioning
M82 ;set extruder to absolute mode
M107 ;start with the fan off
G92 E0; set extruder to 0
G28
G1 Y0.7 F500.0 ; move out of print volume
G1 X60.0 E9 F500.0 ; start purge line
G1 X100.0 E12.5 F500.0 ; finish purge line
G1 Z5.0 E12.0 F500.0 ; raise Z before print retract
G92 E0 ;set extruder to 0

Actual Behavior: 
XY homes, then moves to center of build plate. Z homes, then slowly Y move to Y=0.7 then to ~X=50. Then purge line to X=100
Print begins as normal

Thanks for the AWESOME firmware, I really appreciate the work that goes into this!

**Comment by andrivet** [comment]
This works as expected. It is not a bug. However, as it confuses people, I will see if I change it back to the previous position.

**Comment by andrivet** [comment]
Home position is back to (0,0,0). Implemented in Beta 2

**Comment by john-f-chamberlain** [comment]
Is it possible to have an option to use the BLTouch as the Z limit rather than the limit switch? I may be incorrect, but wouldn't that allow for the bed to be in a fixed position (no springs , no adjustment thumb screws) and guarantee that the head won't crash into the bed?

**Comment by andrivet** [comment]
But in this case, how do you measure the distance between the nozzle and the BLtouch (trigger point), i.e. M851? I have followed what is recommended by Marlin: http://marlinfw.org/docs/gcode/M851.html

On Apr 7, 2018, at 16:03, Johnathan Chamberlain <notifications@github.com<mailto:notifications@github.com>> wrote:


Is it possible to have an option to use the BLTouch as the Z limit rather than the limit switch? I may be incorrect, but wouldn't that allow for the bed to be in a fixed position (no springs , no adjustment thumb screws) and guarantee that the head won't crash into the bed?

**Comment by Titus142** [comment]
Awesome. If i hit home z will it go to xy 00 or will it home wherever xy is
currently?

**Comment by andrivet** [comment]
wherever xy is currently

On Apr 7, 2018, at 16:23, Titus142 <notifications@github.com<mailto:notifications@github.com>> wrote:

Awesome. If i hit home z will it go to xy 00 or will it home wherever xy is
currently?
