### ISSUE TITLE
Revert SD card file sorting to recent first

### ISSUE THREAD

**Issue by biuklija** [andrivet/ADVi3pp#95]
-----------------------------------------------------------
### Feature Request
Files on the SD card, after folders, are sorted alphabetically. The old sorting method (newest files first) was much more practical because it enabled easier access to the last sliced file (which is most of the times the one you want to print)

------------------------------------------------------------

**Comment by biuklija** [comment]
Files are sorted according to the filename only if there are folders present. Should this be classifed as a bug instead?

**Comment by DynaMight1124** [comment]
Just to add a little bit onto this. It is a little annoying, I've recently upgraded from v2.1 to 3.0 beta and noticed my newly added files were not at the top as they've always been. Strangely enough they're right at the bottom but in then in date order with the newer ones since I upgraded at the 'top' of the list. A fix for this would be awesome. You can see theres been massive improvements between betas so thank you for that.

**Comment by supergregg** [comment]
Yes i would like to ad to this. Maybe even a feature for selecting sort order? Like a button on the screen to cycle, Alphabeticly, Date and what ever more and a Default.

**Comment by andrivet** [comment]
@supergregg No, this will not happen. It takes too much memory.

**Comment by galfisk** [comment]
Then would it be possible to simply invert the order of file list from how it's currently displayed? That would in most circumstances put the newest files on top. Since people usually want to print the latest file added to the card, this'd be a nice usability improvement. The original Wanhao firmware does something like this.

**Comment by andrivet** [comment]
I just checked and for a long time, ADVi3++ uses SDCARD_RATHERRECENTFIRST. As Marlin's configuration says:

> Reverse SD sort to show "more recent" files first, according to the card's FAT. Since the FAT gets out of order with usage, SDCARD_SORT_ALPHA is recommended.

So most of the time, files are listed in reverse order (latest first). But this is dependent of what your are doing with your SD card. If you are often removing files from it, the files will be in any order. The solution: reformat the SD card and put back the files your want.
